#include <stdio.h>

int main(void){
    int M,D;
    scanf("%d%d",&M,&D);
    if(M==1){
        if(D>=21){
            printf("Aquarius\n");
        }else{
            printf("Capricorn\n");
        }
    }
    if(M==2){
        if(D>=19){
            printf("Pisces\n");
        }else{
            printf("Aquarius\n");
        }
    }
    if(M==3){
        if(D>=21){
            printf("Aries\n");
        }else{
            printf("Pisces\n");
        }
    }
    if(M==4){if(D>=21){
            printf("Taurus\n");
        }else{
            printf("Aries\n");
        }}
    if(M==5){if(D>=22){
            printf("Gemini\n");
        }else{
            printf("Taurus\n");
        }}
    if(M==6){if(D>=22){
            printf("Cancer\n");
        }else{
            printf("Gemini\n");
        }}
    if(M==7){if(D>=23){
            printf("Leo\n");
        }else{
            printf("Cancer\n");
        }}
    if(M==8){if(D>=24){
            printf("Virgo\n");
        }else{
            printf("Leo\n");
        }}
    if(M==9){if(D>=24){
            printf("Libra\n");
        }else{
            printf("Virgo\n");
        }}
    if(M==10){if(D>=24){
            printf("Scorpio\n");
        }else{
            printf("Libra\n");
        }}
    if(M==11){if(D>=23){
            printf("Sagittarius\n");
        }else{
            printf("Scorpio\n");
        }}
    if(M==12){if(D>=22){
            printf("Capricorn\n");
        }else{
            printf("Sagittarius\n");
        }}
}